#!/bin/bash -ex
#
# unreliable-town-clock-bootstrap
#
# http://townclock.io
#

sns_topic_arn="$1"
region="$2"
support="$3"
clock_period="$4"

echo "INSTANCE CONFIGURATION START"

sudo apt-get update
sudo apt-get install -y awscli ntp supervisor

publish_source=https://raw.githubusercontent.com/tophatmonocle/alestic-unreliable-town-clock/master/unreliable-town-clock-publish
publish=/usr/local/bin/unreliable-town-clock-publish
curl -s --location --retry 10 -o $publish $publish_source
chmod +x $publish

# Create Python script
mkdir -p /clock
cat > /clock/clock.py << EOF
import threading
from subprocess import call
def f():
	call(["$publish", "$sns_topic_arn", "$region", "$clock_period"])
	threading.Timer(10, f).start()
f()
EOF

# Create init script
cat > /etc/init/clock.conf << EOF
start on runlevel [2345]
stop on runlevel [016]

respawn
exec python /clock/clock.py
EOF

sudo service clock start

echo "INSTANCE CONFIGURATION COMPLETE"
